package testes.javaORB.StockObjects;

/**
 * StockObjects/UnknownHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public final class UnknownHolder implements org.omg.CORBA.portable.Streamable {
	public testes.javaORB.StockObjects.Unknown value = null;

	public UnknownHolder() {
	}

	public UnknownHolder(testes.javaORB.StockObjects.Unknown initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = testes.javaORB.StockObjects.UnknownHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		testes.javaORB.StockObjects.UnknownHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return testes.javaORB.StockObjects.UnknownHelper.type();
	}

}
