package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA



/**
 * Devolucao generated by hbm2java
 */
public class Devolucao  implements java.io.Serializable {


     private long operacaoNumero;
     private Operacao operacao;
     private Exemplar exemplar;
     private String descricao;

    public Devolucao() {
    }

	
    public Devolucao(long operacaoNumero, Operacao operacao, Exemplar exemplar) {
        this.operacaoNumero = operacaoNumero;
        this.operacao = operacao;
        this.exemplar = exemplar;
    }
    public Devolucao(long operacaoNumero, Operacao operacao, Exemplar exemplar, String descricao) {
       this.operacaoNumero = operacaoNumero;
       this.operacao = operacao;
       this.exemplar = exemplar;
       this.descricao = descricao;
    }
   
    public long getOperacaoNumero() {
        return this.operacaoNumero;
    }
    
    public void setOperacaoNumero(long operacaoNumero) {
        this.operacaoNumero = operacaoNumero;
    }
    public Operacao getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(Operacao operacao) {
        this.operacao = operacao;
    }
    public Exemplar getExemplar() {
        return this.exemplar;
    }
    
    public void setExemplar(Exemplar exemplar) {
        this.exemplar = exemplar;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


