package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA



/**
 * ExemplarId generated by hbm2java
 */
public class ExemplarId  implements java.io.Serializable {


     private long codigo;
     private long numero;

    public ExemplarId() {
    }

    public ExemplarId(long codigo, long numero) {
       this.codigo = codigo;
       this.numero = numero;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExemplarId) ) return false;
		 ExemplarId castOther = ( ExemplarId ) other; 
         
		 return (this.getCodigo()==castOther.getCodigo())
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCodigo();
         result = 37 * result + (int) this.getNumero();
         return result;
   }   


}


