package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Exemplar generated by hbm2java
 */
public class Exemplar  implements java.io.Serializable {


     private ExemplarId id;
     private Material material;
     private Set emprestimos = new HashSet(0);
     private Set devolucaos = new HashSet(0);

    public Exemplar() {
    }

	
    public Exemplar(ExemplarId id, Material material) {
        this.id = id;
        this.material = material;
    }
    public Exemplar(ExemplarId id, Material material, Set emprestimos, Set devolucaos) {
       this.id = id;
       this.material = material;
       this.emprestimos = emprestimos;
       this.devolucaos = devolucaos;
    }
   
    public ExemplarId getId() {
        return this.id;
    }
    
    public void setId(ExemplarId id) {
        this.id = id;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Set getEmprestimos() {
        return this.emprestimos;
    }
    
    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }
    public Set getDevolucaos() {
        return this.devolucaos;
    }
    
    public void setDevolucaos(Set devolucaos) {
        this.devolucaos = devolucaos;
    }




}


