package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro  implements java.io.Serializable {


     private long materialCodigo;
     private Material material;
     private String editora;
     private String autor;
     private BigDecimal edicao;
     private BigDecimal anopublicacao;
     private Set reservas = new HashSet(0);

    public Livro() {
    }

	
    public Livro(long materialCodigo, Material material) {
        this.materialCodigo = materialCodigo;
        this.material = material;
    }
    public Livro(long materialCodigo, Material material, String editora, String autor, BigDecimal edicao, BigDecimal anopublicacao, Set reservas) {
       this.materialCodigo = materialCodigo;
       this.material = material;
       this.editora = editora;
       this.autor = autor;
       this.edicao = edicao;
       this.anopublicacao = anopublicacao;
       this.reservas = reservas;
    }
   
    public long getMaterialCodigo() {
        return this.materialCodigo;
    }
    
    public void setMaterialCodigo(long materialCodigo) {
        this.materialCodigo = materialCodigo;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getEditora() {
        return this.editora;
    }
    
    public void setEditora(String editora) {
        this.editora = editora;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public BigDecimal getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(BigDecimal edicao) {
        this.edicao = edicao;
    }
    public BigDecimal getAnopublicacao() {
        return this.anopublicacao;
    }
    
    public void setAnopublicacao(BigDecimal anopublicacao) {
        this.anopublicacao = anopublicacao;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


