package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private long codigo;
     private String titulo;
     private Set exemplars = new HashSet(0);
     private Set revistas = new HashSet(0);
     private Set livros = new HashSet(0);

    public Material() {
    }

	
    public Material(long codigo, String titulo) {
        this.codigo = codigo;
        this.titulo = titulo;
    }
    public Material(long codigo, String titulo, Set exemplars, Set revistas, Set livros) {
       this.codigo = codigo;
       this.titulo = titulo;
       this.exemplars = exemplars;
       this.revistas = revistas;
       this.livros = livros;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getExemplars() {
        return this.exemplars;
    }
    
    public void setExemplars(Set exemplars) {
        this.exemplars = exemplars;
    }
    public Set getRevistas() {
        return this.revistas;
    }
    
    public void setRevistas(Set revistas) {
        this.revistas = revistas;
    }
    public Set getLivros() {
        return this.livros;
    }
    
    public void setLivros(Set livros) {
        this.livros = livros;
    }




}


