package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private long operacaoNumero;
     private Operacao operacao;
     private Livro livro;
     private String descricao;

    public Reserva() {
    }

	
    public Reserva(long operacaoNumero, Operacao operacao, Livro livro) {
        this.operacaoNumero = operacaoNumero;
        this.operacao = operacao;
        this.livro = livro;
    }
    public Reserva(long operacaoNumero, Operacao operacao, Livro livro, String descricao) {
       this.operacaoNumero = operacaoNumero;
       this.operacao = operacao;
       this.livro = livro;
       this.descricao = descricao;
    }
   
    public long getOperacaoNumero() {
        return this.operacaoNumero;
    }
    
    public void setOperacaoNumero(long operacaoNumero) {
        this.operacaoNumero = operacaoNumero;
    }
    public Operacao getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(Operacao operacao) {
        this.operacao = operacao;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


