package ic.tcc00175.biblioteca.controller;
// Generated Sep 19, 2013 8:00:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long matricula;
     private String nome;
     private Set operacaos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long matricula, String nome) {
        this.matricula = matricula;
        this.nome = nome;
    }
    public Usuario(long matricula, String nome, Set operacaos) {
       this.matricula = matricula;
       this.nome = nome;
       this.operacaos = operacaos;
    }
   
    public long getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(long matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getOperacaos() {
        return this.operacaos;
    }
    
    public void setOperacaos(Set operacaos) {
        this.operacaos = operacaos;
    }




}


